### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vincentmaule** [OptimisticShaggy/LAB-101-html-multiple-pages#1]
## Build a fansite for books, movies, video games, or anything else

@egillespie Can you take a look at this? It's [hosted here](https://optimisticshagg-html-multiple.surge.sh/) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`) -- we want to make sure you practice multiple levels of nested routes
- [x] Every page includes links to the homepage and list page (although pages do not have to link to themselves)

careless-form.surge.sh

**Comment by egillespie** [comment]
Your site has a nice clean look to it and I like all the valid HTML. 😁  I see a homepage and three pages for the different Expanse factions as well, and they are all nested within a `/factions` route to boot. 👍 

I have a couple of recommendations to improve what you've got here and better leverage nested routes. Can you try these out?

### Create a `/factions/index.html` file to list the factions

It looks like all of your pages include links to each of the three factions. This is certainly helpful, but it would require changing an increasing number of pages each time a new factions was added to the Expanse "universe".

To avoid this and touch on requirements 3 and 5 more strongly, could you mind adding a `/factions/index.html` page that lists the factions, then replace your three links on all pages to instead point at the list page: `/factions`?

This way, if factions are changed, you only need to change `/factions/index.html` and it makes use of the currently-empty `/factions` routes.

### Update images

The HTML is all valid, but the images don't seem to be rendering when I view your hosted site:

![image](https://user-images.githubusercontent.com/5572255/97786384-92a5c280-1b81-11eb-9c76-229409d7fcc6.png)

Would you mind updating the image addresses so pictures of the factions and show appear as expectd?

### Update heading on OPA page

It looks like the heading on the OPA page says "Mars." Would you mind updating this to reflect the real page title?

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🚀

**Comment by vincentmaule** [comment]
Managed to do everything and was able to revamp the pages for each of the factions. Thank you for pointing these small issues out as well as the title that I missed. I went through the code and verified there are no discrepancies via validator, discrepancies with titles and also verified my sentences.

**Comment by egillespie** [comment]
I really like all of the adjustments you've made to your site! The extra `<<Factions` link at the top is a really convenient and considerate touch. 🤘 

The layout is really consistent and looks so nice. Great job on this project! 👏 :shipit:

**Comment by vincentmaule** [comment]
Great to learn from this project, especially linking to some pages. Learned more from how to link and working with Skeleton.
